version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: guestbook
      MYSQL_ROOT_PASSWORD: root