apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-db-deployment
spec:
  selector:
    matchLabels:
      name: guestbook-db
  template:
    metadata:
      labels:
        name: guestbook-db
    spec:
      containers:
      - name: guestbook-db
        image: mysql:8.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_DATABASE
            value: guestbook
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 3306
