apiVersion: v1
kind: Pod
metadata:
  name: guestbook-api
  labels:
    name: guestbook-api
spec:
  containers:
  - name: guestbook-api
    image: laterality/guestbook-api:latest
    resources:
      limits:
        memory: "1Gi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  - name: guestbook-db
    image: mysql:8.0
    env:
    - name: MYSQL_DATABASE
      value: guestbook
    - name: MYSQL_ROOT_PASSWORD
      value: root
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
        - containerPort: 3306
