spring.r2dbc:
  url: r2dbc:mysql://localhost:3306/guestbook
  name: guestbook
  username: root
  password: root
management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
